### ISSUE TITLE
Improving the game master

### ISSUE THREAD

**Issue by s-will** [ViennaAPBC/APBC#63]
Hi @ViennaAPBC/apbc 

the game master program 6nimmt.py could really need some more attention.

1) I think it would be cool to have prettier output such that humans (i.e. we) can see what is going on more easily. (One could switch between current logging output and pretty output via command line parameter.)
How could this look like?

2) The master should keep additional statistics on the played games (recall that the server can play e.g. 1000 games in a row). At least we should sum the penalties, but there are a lot more interesting data (how often takes each player rows, what are the row differences, ranks in the playing order etc) Be creative:) and feel free to discuss ideas.

Who  suggests changes? Preferrably in branch game-devel or even better a new PR.

**Comment by zouroboros** [comment]
I've added #66 and #67 for features that would make it easier to analyse games and for a visualisation of the games.

**Comment by zouroboros** [comment]
I wrote a script to gather statistics for myself, I merged it into the game master, see: #69.

**Comment by s-will** [comment]
I merged @zouroboros ' statistics code into game-devel. While this code writes statistics in the game history file, It would be even more convenient to compute such statistics in a post-processing step from the history file. It seems like this needs only little refactoring based on Mark's code.

**Comment by s-will** [comment]
@zouroboros:
As far as I see, the history contains one status per round, which is written at the beginning of each round. This means that the last history entry does *not* contain the final penalties! Moreover, the
final game configuration is not recorded. Thus,it seems reasonable to add the final state (after the cards of the last round are played) such that the history contains all relevant information. Do you agree; would you change this? 

Currently, while not the complete final status is recorded, the final penalties are stored in 'result'. Of course, if you add the final status, the result entry could be dropped as well.

**Comment by zouroboros** [comment]
@s-will could merge the game-devel#statistics branch again (#70). I actually had implemented an option to save the statistics in nicer format than json, I just forgot to push it.

**Comment by chrisuWa** [comment]
Problem with error handling:
when calling 6nimmt.py like this:
$ python3 6nimmt.py Player#FirstCard.py Player#random.py Player#random.py 
(without giving the path to the players like ./Player#something) it raises a Warning that it could not find the players:
[WARNING]	Exception FileNotFoundError raised.
but plays nontheless with the given players.
[INFO]	-------------------- Play round 1--------------------
[INFO]	Game status: {'players': [{'index': 0, 'progname': 'Player#FirstCard.py', 'name': 'Player 1'}, {'index': 1, 'progname': 'Player#random.py', 'name': 'Player 2'}, {'index': 2, 'progname': 'Player#random.py', 'name': 'Player 3'}], 'penalties': [0, 0, 0], 'time_limit': 10, 'hands': [[4, 9, 12, 21, 30, 35, 47, 51, 63, 99], [11, 23, 28, 41, 46, 50, 55, 57, 75, 93], [2, 3, 37, 43, 49, 60, 76, 84, 86, 104]], 'number_of_cards': 104, 'removed': [], 'rows': [[31], [34], [81], [58]]}
[WARNING]	Exception FileNotFoundError raised.
[WARNING]	Exception FileNotFoundError raised.
[WARNING]	Exception FileNotFoundError raised.
[INFO]	Players choose [4, 50, 37]

$ python3 6nimmt.py ./Player#FirstCard.py ./Player#random.py ./Player#random.py 
works fine.

**Comment by s-will** [comment]
chrisuWa's issues fixed in PR #73

**Comment by Santhel** [comment]
@s-will this is my first comment in this section, better late than never
if a player plays a card, which he does not have in his hand, or basically any other integer, the game will crash:

Traceback (most recent call last):
  File "6nimmt1.2.py", line 370, in <module>
    games.append(play_game(cards, players, args.number_of_cards_per_player, args.number_of_rows, args.time_limit))
  File "6nimmt1.2.py", line 258, in play_game
    place_cards_in_round(game_status, choices)
  File "6nimmt1.2.py", line 187, in place_cards_in_round
    status["hands"][player_index].remove(card)
ValueError: list.remove(x): x not in list

the player should receive the same penalty as a player, who does not play any card at all

I tried to handle it myself, but I'm not good at handling errors and exceptions, so I added an if-statement to the "place_cards_in_round"-function, which works:

`def place_cards_in_round(status, choices):
    choices = list(enumerate(choices))
    lowest_end = min([row[-1] for row in status['rows']] )
    choices.sort(key = lambda x: (x[1] < lowest_end, x[1]))

    for player_index,card in choices:
        logging.debug("Place "+str(card)+" for player '"+status["players"][player_index]["name"]+"'" )

        ## remove the card from the players hand
        if card not in status["hands"][player_index]:
          card = random.choice(status["hands"][player_index])
          status["penalties"][player_index] += penalty_invalid_response
        status["hands"][player_index].remove(card)
        ## place the card
        status["penalties"][player_index] += place_card(status,card)`

**Comment by s-will** [comment]
Hi @santhel,
great that you spotted the bug. An even better place to fix it would be after https://github.com/ViennaAPBC/APBC/blob/game-devel/A6/6nimmt.py#L249
If your new test fails (i.e. card is not in hand), you could raise an exception like
```
if choice not in player_status["hand"]:
    raise Exception
```
Could you please test this and then push the change to a new branch, let's say game-devel#handle-wrong-card and create a PR?
